### ISSUE TITLE
获取输入的latex代码

### ISSUE THREAD

**Issue by loyalpartner** [SugarTurboS/Formula-Editor#3]
请问如何获取输入的latex代码呢

**Comment by SugarTeam** [comment]
@Demian1996

**Comment by Demian1996** [comment]
@loyalpartner 已新增md文件，补充了信令及相关可用示例，[点击访问](https://github.com/SugarTurboS/Formula-Editor/blob/dev-2.0.23/src/editor/command.md)

**Comment by loyalpartner** [comment]
感谢！
