### ISSUE TITLE
生成的公式无法复制。导出的文档不完善

### ISSUE THREAD

**Issue by huatiankuaile** [SugarTurboS/Formula-Editor#5]
生成的公式无法复制粘贴，可以生成图片。
建议文档标注一下，提高实用性。

**Comment by Demian1996** [comment]
#3 已给出信令相关的接口文档，可使用该文档中的示例测试导出后的src，我补充一下readme。

**Comment by Demian1996** [comment]
@huatiankuaile readme已补充导出公式的相关示例
